; Listing generated by Microsoft (R) Optimizing Compiler Version 19.31.31105.0 

; Generated by VC++ for Common Language Runtime
.file "D:\C++ Projects\CppDataEntry3\CppDataEntry3\x64\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.obj"
.global	
.global	
	.bss
.local	,4
.local	,4
; Function compile flags: /Odtp
; File D:\C++ Projects\CppDataEntry3\CppDataEntry3\predefined C++\CLI attribute types (compiler internal)
	.text
	.comdat	any, ??0CppInlineNamespaceAttribute@?A0x1e878bb9@vc.cppcli.attributes@@$$FQE$AAM@PE$AAVString@System@@@Z
.global	??0CppInlineNamespaceAttribute@?A0x1e878bb9@vc.cppcli.attributes@@$$FQE$AAM@PE$AAVString@System@@@Z ; ??0CppInlineNamespaceAttribute@?A0x1e878bb9@vc.cppcli.attributes@@$$FQE$AAM@PE$AAVString@System@@@Z
??0CppInlineNamespaceAttribute@?A0x1e878bb9@vc.cppcli.attributes@@$$FQE$AAM@PE$AAVString@System@@@Z: ; ??0CppInlineNamespaceAttribute@?A0x1e878bb9@vc.cppcli.attributes@@$$FQE$AAM@PE$AAVString@System@@@Z
;	.proc.def	D:V(P)

; Function Header:
; max stack depth = 1
; function size = 7 bytes
; local varsig tk = 0x0 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0xBE51E2E5).class (token:0xBE51E2E7)

;	.proc.beg

	ldarg.0				; this$
	call		??0Attribute@System@@$$FIE$AAM@XZ
	ret		
 .end ??0CppInlineNamespaceAttribute@?A0x1e878bb9@vc.cppcli.attributes@@$$FQE$AAM@PE$AAVString@System@@@Z ; ??0CppInlineNamespaceAttribute@?A0x1e878bb9@vc.cppcli.attributes@@$$FQE$AAM@PE$AAVString@System@@@Z
;	.proc.end.void
